### default supported ROS message types:
# sensor_msgs/Imu
# geometry_msgs/Twist
# std_msgs/String
# (modify/add in ros_sub_pub.hpp if you need more)
### max number of send_topics supported: 50

### list all <IPname: IP> here (IPname can be set arbitrarily) ###
IP:
  self: "*" # '*' stands for all self IPs
  gcs: 192.168.101.138
  gcs2: 192.168.101.10
  drone1: 192.168.101.151
  drone2: 192.168.101.152
  drone3: 192.168.101.153
  drone4: 192.168.101.154
  drone5: 192.168.101.155

  drone6: 192.168.101.57
  drone7: 192.168.101.58
  drone8: 192.168.101.62
  drone9: 192.168.101.64
  drone10: 192.168.101.65

  neighbor: 127.0.0.1 # modify to the IP of other machines

####### Send these ROS messages to remote robots #######
## if no send_topics needed, comment all these out
## 30xx  drone -> ground station
## 31xx  drone -> drone
## 32xx  ground station -> drone
send_topics:
  - topic_name: /broadcast_traj_to_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: self
    srcPort: 3200
    max_freq: 10
  - topic_name: /joystick_from_bridge
    msg_type: sensor_msgs/Joy
    srcIP: self
    srcPort: 3201
    max_freq: 10

  - topic_name: /qual_1/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3210
    max_freq: 10
  - topic_name: /qual_2/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3211
    max_freq: 10
  - topic_name: /qual_3/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3212
    max_freq: 10
  - topic_name: /qual_4/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3213
    max_freq: 10
  - topic_name: /qual_5/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3214
    max_freq: 10
  - topic_name: /qual_6/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3215
    max_freq: 10
  - topic_name: /qual_7/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3216
    max_freq: 10
  - topic_name: /qual_8/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3217
    max_freq: 10
  - topic_name: /qual_9/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3218
    max_freq: 10
  - topic_name: /qual_10/odometry
    msg_type: nav_msgs/Odometry
    srcIP: self
    srcPort: 3219
    max_freq: 10


####### receive these ROS messages from remote robots #######
## if no recv_topics needed, comment all these out
recv_topics:
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone1
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone2
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone3
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone4
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone5
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone6
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone7
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone8
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone9
    srcPort: 3001
  - topic_name: /broadcast_traj_from_planner
    msg_type: traj_utils/MINCOTraj
    srcIP: drone10
    srcPort: 3001

  # Visualization
  - topic_name: /quad_1/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3002
  - topic_name: /quad_2/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3002
  - topic_name: /quad_3/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3002
  - topic_name: /quad_4/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3002
  - topic_name: /quad_5/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3002
  - topic_name: /quad_6/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3002
  - topic_name: /quad_7/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3002
  - topic_name: /quad_8/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone8
    srcPort: 3002
  - topic_name: /quad_9/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone9
    srcPort: 3002
  - topic_name: /quad_10/odom_visualization/path
    msg_type: visualization_msgs/Marker
    srcIP: drone10
    srcPort: 3002

  - topic_name: /quad_1/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3003
  - topic_name: /quad_2/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3003
  - topic_name: /quad_3/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3003
  - topic_name: /quad_4/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3003
  - topic_name: /quad_5/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3003
  - topic_name: /quad_6/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3003
  - topic_name: /quad_7/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3003
  - topic_name: /quad_8/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone8
    srcPort: 3003
  - topic_name: /quad_9/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone9
    srcPort: 3003
  - topic_name: /quad_10/ego_planner_node/optimal_list
    msg_type: visualization_msgs/Marker
    srcIP: drone10
    srcPort: 3003

  - topic_name: /quad_1/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone1
    srcPort: 3004
  - topic_name: /quad_2/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone2
    srcPort: 3004
  - topic_name: /quad_3/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone3
    srcPort: 3004
  - topic_name: /quad_4/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone4
    srcPort: 3004
  - topic_name: /quad_5/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone5
    srcPort: 3004
  - topic_name: /quad_6/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone6
    srcPort: 3004
  - topic_name: /quad_7/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone7
    srcPort: 3004
  - topic_name: /quad_8/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone8
    srcPort: 3004
  - topic_name: /quad_9/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone9
    srcPort: 3004
  - topic_name: /quad_10/ego_planner_node/grid_map/occupancy_inflate
    msg_type: visualization_msgs/Marker
    srcIP: drone10
    srcPort: 3004